### ISSUE TITLE
Game Keeps Crashing

### ISSUE THREAD

**Issue by Wh00ppY** [KaptainWutax/SeedCracker#116]
Everytime I load into a world with the mod loaded I will get the hashed seed message, and then my game will freeze for a second and crash. The crash report says, "The game crashed whilst tesselating block model. Error: java.lang.NoSuchFieldError: field_9473. Exit Code: -1." Not really sure if it's an issue with my computer but I have an i5-9600k (not overclocked), rtx 2060 SUPER.

**Comment by KaptainWutax** [comment]
I need a crash report...

**Comment by Wh00ppY** [comment]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/16/20 7:29 PM
Description: Tesselating block model

java.lang.NoSuchFieldError: field_9473
	at net.minecraft.class_638.handler$zzd000$getGeneratorStoredBiome(class_638.java:894)
	at net.minecraft.class_638.method_22387(class_638.java)
	at net.minecraft.class_4538.method_16359(class_4538.java:65)
	at net.minecraft.class_4546.method_22396(class_4546.java:65)
	at net.minecraft.class_4547.method_22396(class_4547.java:8)
	at net.minecraft.class_4543.method_22393(class_4543.java:27)
	at net.minecraft.class_4538.method_23753(class_4538.java:37)
	at net.minecraft.class_638.method_23780(class_638.java:788)
	at net.minecraft.class_638.method_23781(class_638.java:770)
	at net.minecraft.class_638$$Lambda$5119/2028350706.getAsInt(Unknown Source)
	at net.minecraft.class_4700.method_23770(class_4700.java:43)
	at net.minecraft.class_638.method_23752(class_638.java:770)
	at net.minecraft.class_853.method_23752(class_853.java:137)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.method_1693(class_324.java:48)
	at net.minecraft.class_324$$Lambda$2587/1281799129.getColor(Unknown Source)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.minecraft.class_778.method_23073(class_778.java:141)
	at net.minecraft.class_778.method_3363(class_778.java:127)
	at net.minecraft.class_778.method_3361(class_778.java:76)
	at net.minecraft.class_778.method_3374(class_778.java:47)
	at net.minecraft.class_776.method_3355(class_776.java:61)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:512)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:434)
	at net.minecraft.class_846.method_22757(class_846.java:136)
	at net.minecraft.class_846$$Lambda$5197/571726146.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_638.handler$zzd000$getGeneratorStoredBiome(class_638.java:894)
	at net.minecraft.class_638.method_22387(class_638.java)
	at net.minecraft.class_4538.method_16359(class_4538.java:65)
	at net.minecraft.class_4546.method_22396(class_4546.java:65)
	at net.minecraft.class_4547.method_22396(class_4547.java:8)
	at net.minecraft.class_4543.method_22393(class_4543.java:27)
	at net.minecraft.class_4538.method_23753(class_4538.java:37)
	at net.minecraft.class_638.method_23780(class_638.java:788)
	at net.minecraft.class_638.method_23781(class_638.java:770)
	at net.minecraft.class_638$$Lambda$5119/2028350706.getAsInt(Unknown Source)
	at net.minecraft.class_4700.method_23770(class_4700.java:43)
	at net.minecraft.class_638.method_23752(class_638.java:770)
	at net.minecraft.class_853.method_23752(class_853.java:137)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.method_1693(class_324.java:48)
	at net.minecraft.class_324$$Lambda$2587/1281799129.getColor(Unknown Source)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.minecraft.class_778.method_23073(class_778.java:141)
	at net.minecraft.class_778.method_3363(class_778.java:127)
	at net.minecraft.class_778.method_3361(class_778.java:76)

-- Block model being tesselated --
Details:
	Block: Block{minecraft:grass_block}[snowy=false]
	Block location: World: (-81,64,192), Chunk: (at 15,4,0 in -6,12; contains blocks -96,0,192 to -81,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.class_778.method_3374(class_778.java:47)

-- Block being tesselated --
Details:
	Block: Block{minecraft:grass_block}[snowy=false]
	Block location: World: (-81,64,192), Chunk: (at 15,4,0 in -6,12; contains blocks -96,0,192 to -81,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.class_776.method_3355(class_776.java:61)

-- Affected level --
Details:
	All players: 1 total; [class_746['Wh00ppY43'/382, l='ClientLevel', x=-255.56, y=73.12, z=56.22]]
	Chunk stats: Client Chunk Cache: 841, 532
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,66,64), Chunk: (at 0,4,0 in -16,4; contains blocks -256,0,64 to -241,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 200 game time, 200 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_846.method_22755(class_846.java:140)
	at net.minecraft.class_846$$Lambda$5198/1732510547.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1058122048 bytes (1009 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.10.1+build.209-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz

**Comment by KaptainWutax** [comment]
Cannot reproduce, the field is present. Are you sure you're using the right jar?

**Comment by Wh00ppY** [comment]
Not really sure.

**Comment by ChxGuillaume** [comment]
Removing all other mods and updating to lasted fixed the issue but i don't rly understand why other mods would cause problems :/

**Comment by KaptainWutax** [comment]
That's just not a seed cracker crash.
