### ISSUE TITLE
Game Crashes in the end in the new Snapshots

### ISSUE THREAD

**Issue by PhoenixXKN** [KaptainWutax/SeedCracker#182]
I'm on a 20w48a server with vanilla terrain, and when I went to the end, the game crashed with this message:
```
Unreported exception thrown!
java.lang.NoSuchMethodError: net.minecraft.class_287.method_1328(ILnet/minecraft/class_293;)V
	at kaptainwutax.seedcracker.render.Line.render(Line.java:40)
	at kaptainwutax.seedcracker.render.Cuboid.render(Cuboid.java:53)
	at kaptainwutax.seedcracker.finder.Finder$$Lambda$4495/1096321686.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at kaptainwutax.seedcracker.finder.Finder.render(Finder.java:80)
	at kaptainwutax.seedcracker.finder.FinderQueue.lambda$renderFinders$3(FinderQueue.java:67)
	at kaptainwutax.seedcracker.finder.FinderQueue$$Lambda$4363/537255019.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at kaptainwutax.seedcracker.finder.FinderQueue.renderFinders(FinderQueue.java:65)
	at kaptainwutax.seedcracker.SeedCracker$$Lambda$2501/1547802438.accept(Unknown Source)
	at kaptainwutax.seedcracker.render.RenderQueue.lambda$onRender$0(RenderQueue.java:49)
	at kaptainwutax.seedcracker.render.RenderQueue$$Lambda$4360/1957610983.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at kaptainwutax.seedcracker.render.RenderQueue.onRender(RenderQueue.java:49)
	at net.minecraft.class_3694.handler$zza000$swap(class_3694.java:515)
	at net.minecraft.class_3694.method_15405(class_3694.java)
	at net.minecraft.class_757.method_3188(class_757.java:759)
	at net.minecraft.class_757.method_3192(class_757.java:553)
	at net.minecraft.class_310.method_1523(class_310.java:1052)
	at net.minecraft.class_310.method_1514(class_310.java:688)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```
So from what I can tell, the new version doesn't support the drawing of the colored boxes that used to appear around the end bedrock(or some other thing involving visual lines), so it *might* be able to be fixed by disabling it? Though again, i'm not sure, it could be that the method mappings have changed entirely in the snapshot. I'm using the newest beta release.

**Comment by MrAppu** [comment]
I think there might be some code changes in the snapshots compared to 1.16, like there are some new biomes right?
